openapi: '3.0.0'
info:
  version: 1.0.0
  title: Asliddin Muzafarzoda
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /updates:
    get:
      summary: List all updates
      operationId: listUpdates
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of updates
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Updates'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create update
      operationId: createUpdate
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /updates/{updateId}:
    get:
      summary: Get specific update
      operationId: showUpdateById
      parameters:
        - name: updateId
          in: path
          required: true
          description: The id of the update to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Updates'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /announcements:
    get:
      summary: List announcements
      operationId: listAnnouncements
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of announcements
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announcements'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create announcement
      operationId: createAnnouncement
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /announcements/{announcementId}:
    get:
      summary: Get announcement
      operationId: showAnnouncementById
      parameters:
        - name: announcementId
          in: path
          required: true
          description: The id of the announcement to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announcements'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Update:
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
    Updates:
      type: array
      items:
        $ref: '#/components/schemas/Update'
    Announcement:
      required:
        - id
        - message
      properties:
        id:
          type: integer
          format: int64
        message:
          type: string
        category:
          type: string
    Announcements:
      type: array
      items:
        $ref: '#/components/schemas/Announcement'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string